# Generated by Django 5.0.3 on 2024-03-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0002_alter_calorieexpenditure_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CalorieExpenditure",
            new_name="Expenditure",
        ),
        migrations.RenameModel(
            old_name="Food",
            new_name="Intake",
        ),
        migrations.AlterModelOptions(
            name="expenditure",
            options={"verbose_name_plural": "Expenditures"},
        ),
        migrations.AlterModelOptions(
            name="intake",
            options={"verbose_name_plural": "Intakes"},
        ),
    ]
