# Generated by Django 5.0.3 on 2024-03-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="goal_daily_calorie_delta",
            field=models.IntegerField(default=0),
        ),
    ]
