# Generated by Django 5.0.3 on 2024-03-12 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0005_userprofile_goal_daily_calorie_delta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weight",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
