# Generated by Django 5.0.3 on 2024-03-18 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0006_alter_weight_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
