# Generated by Django 5.0.3 on 2024-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0007_alter_intake_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="previous_day_surplus_calories",
            field=models.IntegerField(default=0),
        ),
    ]
