# Generated by Django 5.0.3 on 2024-03-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0008_userprofile_previous_day_surplus_calories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="previous_day_surplus_calories",
            new_name="adjustment",
        ),
    ]
